namespace InspectV2.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SeedEvents : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO [dbo].[Events] ([Title], [Body], [Link], [EventDate], [SeatCount], [Company], [Location]) VALUES (N'XYZ Hackathon 2019', N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dolorum, veritatis sequi delectus autem iure mollitia quisquam tenetur, facilis voluptate nisi earum qui! Lorem ipsum dolor sit amet consectetur adipisicing elit.Officia suscipit maiores ex maxime nesciunt expedita est repellat quasi dolores in.Odit illo consequuntur veritatis vel quo harum numquam ea ut recusandae, consequatur quaerat ipsam laudantium assumenda amet error, officiis maiores in fugit molestiae ? Aliquid dolorem esse doloremque quos ea adipisci dignissimos dolorum eveniet libero iusto.Atque laudantium tenetur minus reprehenderit dolore dignissimos accusantium.Ea sunt nemo illum alias voluptas consequatur officiis hic nostrum ? Harum voluptas quam laboriosam tempora dolores laborum repellat autem, obcaecati odit nihil voluptates, nesciunt delectus.Magni debitis id expedita, illo quod fugit sapiente voluptatem suscipit harum doloribus, optio eius cupiditate ad', N'www.facebook.com' , GETDATE(), 45, N'Selise', N'Dhaka')");
            Sql("INSERT INTO [dbo].[Events] ([Title], [Body], [Link], [EventDate], [SeatCount], [Company], [Location]) VALUES (N'XYZ Hackathon 2019', N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dolorum, veritatis sequi delectus autem iure mollitia quisquam tenetur, facilis voluptate nisi earum qui! Lorem ipsum dolor sit amet consectetur adipisicing elit.Officia suscipit maiores ex maxime nesciunt expedita est repellat quasi dolores in.Odit illo consequuntur veritatis vel quo harum numquam ea ut recusandae, consequatur quaerat ipsam laudantium assumenda amet error, officiis maiores in fugit molestiae ? Aliquid dolorem esse doloremque quos ea adipisci dignissimos dolorum eveniet libero iusto.Atque laudantium tenetur minus reprehenderit dolore dignissimos accusantium.Ea sunt nemo illum alias voluptas consequatur officiis hic nostrum ? Harum voluptas quam laboriosam tempora dolores laborum repellat autem, obcaecati odit nihil voluptates, nesciunt delectus.Magni debitis id expedita, illo quod fugit sapiente voluptatem suscipit harum doloribus, optio eius cupiditate ad', N'www.facebook.com' ,  GETDATE(), 45, N'Daily Stare', N'Dhaka')");
            Sql("INSERT INTO [dbo].[Events] ([Title], [Body], [Link], [EventDate], [SeatCount], [Company], [Location]) VALUES (N'XYZ Hackathon 2019', N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dolorum, veritatis sequi delectus autem iure mollitia quisquam tenetur, facilis voluptate nisi earum qui! Lorem ipsum dolor sit amet consectetur adipisicing elit.Officia suscipit maiores ex maxime nesciunt expedita est repellat quasi dolores in.Odit illo consequuntur veritatis vel quo harum numquam ea ut recusandae, consequatur quaerat ipsam laudantium assumenda amet error, officiis maiores in fugit molestiae ? Aliquid dolorem esse doloremque quos ea adipisci dignissimos dolorum eveniet libero iusto.Atque laudantium tenetur minus reprehenderit dolore dignissimos accusantium.Ea sunt nemo illum alias voluptas consequatur officiis hic nostrum ? Harum voluptas quam laboriosam tempora dolores laborum repellat autem, obcaecati odit nihil voluptates, nesciunt delectus.Magni debitis id expedita, illo quod fugit sapiente voluptatem suscipit harum doloribus, optio eius cupiditate ad', N'www.facebook.com' ,  GETDATE(), 45, N'Therup', N'Dhaka')");
            Sql("INSERT INTO [dbo].[Events] ([Title], [Body], [Link], [EventDate], [SeatCount], [Company], [Location]) VALUES (N'XYZ Hackathon 2019', N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dolorum, veritatis sequi delectus autem iure mollitia quisquam tenetur, facilis voluptate nisi earum qui! Lorem ipsum dolor sit amet consectetur adipisicing elit.Officia suscipit maiores ex maxime nesciunt expedita est repellat quasi dolores in.Odit illo consequuntur veritatis vel quo harum numquam ea ut recusandae, consequatur quaerat ipsam laudantium assumenda amet error, officiis maiores in fugit molestiae ? Aliquid dolorem esse doloremque quos ea adipisci dignissimos dolorum eveniet libero iusto.Atque laudantium tenetur minus reprehenderit dolore dignissimos accusantium.Ea sunt nemo illum alias voluptas consequatur officiis hic nostrum ? Harum voluptas quam laboriosam tempora dolores laborum repellat autem, obcaecati odit nihil voluptates, nesciunt delectus.Magni debitis id expedita, illo quod fugit sapiente voluptatem suscipit harum doloribus, optio eius cupiditate ad', N'www.facebook.com' ,  GETDATE(), 45, N'Brain Storm', N'Dhaka')");
            Sql("INSERT INTO [dbo].[Events] ([Title], [Body], [Link], [EventDate], [SeatCount], [Company], [Location]) VALUES (N'XYZ Hackathon 2019', N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dolorum, veritatis sequi delectus autem iure mollitia quisquam tenetur, facilis voluptate nisi earum qui! Lorem ipsum dolor sit amet consectetur adipisicing elit.Officia suscipit maiores ex maxime nesciunt expedita est repellat quasi dolores in.Odit illo consequuntur veritatis vel quo harum numquam ea ut recusandae, consequatur quaerat ipsam laudantium assumenda amet error, officiis maiores in fugit molestiae ? Aliquid dolorem esse doloremque quos ea adipisci dignissimos dolorum eveniet libero iusto.Atque laudantium tenetur minus reprehenderit dolore dignissimos accusantium.Ea sunt nemo illum alias voluptas consequatur officiis hic nostrum ? Harum voluptas quam laboriosam tempora dolores laborum repellat autem, obcaecati odit nihil voluptates, nesciunt delectus.Magni debitis id expedita, illo quod fugit sapiente voluptatem suscipit harum doloribus, optio eius cupiditate ad', N'www.facebook.com' ,  GETDATE(), 45, N'Google', N'Dhaka')");
            Sql("INSERT INTO [dbo].[Events] ([Title], [Body], [Link], [EventDate], [SeatCount], [Company], [Location]) VALUES (N'XYZ Hackathon 2019', N'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta dolorum, veritatis sequi delectus autem iure mollitia quisquam tenetur, facilis voluptate nisi earum qui! Lorem ipsum dolor sit amet consectetur adipisicing elit.Officia suscipit maiores ex maxime nesciunt expedita est repellat quasi dolores in.Odit illo consequuntur veritatis vel quo harum numquam ea ut recusandae, consequatur quaerat ipsam laudantium assumenda amet error, officiis maiores in fugit molestiae ? Aliquid dolorem esse doloremque quos ea adipisci dignissimos dolorum eveniet libero iusto.Atque laudantium tenetur minus reprehenderit dolore dignissimos accusantium.Ea sunt nemo illum alias voluptas consequatur officiis hic nostrum ? Harum voluptas quam laboriosam tempora dolores laborum repellat autem, obcaecati odit nihil voluptates, nesciunt delectus.Magni debitis id expedita, illo quod fugit sapiente voluptatem suscipit harum doloribus, optio eius cupiditate ad', N'www.facebook.com' ,  GETDATE(), 45, N'Tiger IT', N'Dhaka')");
        }
        
        public override void Down()
        {
        }
    }
}
